### PR TITLE
add podspec

### PR DESCRIPTION
**Pull request by openm1nd**

### CODE REVIEW

**Comment by mickael-menu** [comment]
Thanks @openm1nd. Before bringing back the Podspecs in the libraries, I need a way to validate before each release that they are still working properly. I'm not super familiar with CocoaPods, so it would help if you can also provide a sample workspace integrating R2 CocoaPods dependencies, with a short README explaining how to upgrade to the next version and check this is still working.

**Comment by mickael-menu** [comment]
@openm1nd Any follow-up? I'm wary of merging without a clear way to verify that Podspecs won't break in the next release.

**Comment by mickael-menu** [comment]
Here's a sample repo from @Jokez80 which could help test this out: https://github.com/Jokez80/Podstest

**Review by mickael-menu — APPROVED** [review]

**Comment by Jokez80** [comment]
Yay!

**Pull request merged**
