### PR TITLE
Add PublicationAsset

### PR DESCRIPTION
**Pull request by mickael-menu**
* `PublicationAsset` is a new protocol which can be used to open a publication from various medium, such as a file, a
remote URL or a custom source.
  * `File` was replaced by `FileAsset`, which implements `PublicationAsset`.

### CODE REVIEW

**Comment by alexwhb** [comment]
@mickael-menu I'm playing around with 

```streamer.open(asset: FileAsset(url: url), allowUserInteraction: allowUserInteraction, sender: sender, completion: $0)```

And I'm wondering how / if I can open a remote URL instead of a local File asset with `PublicationAsset`. Is that something that is yet to be implemented or is there a type for that currently?

**Comment by mickael-menu** [comment]
@alexwhb `FileAsset` is only for local files, but there are possibilities for streaming depending on your use case. Could you give a bit more details about the remote file?

Note that you can always implement your own `PublicationAsset`. You just need to return a `Fetcher` instance. `HTTPFetcher` can be used to fetch the resources of a publication remotely. See this relevant issue: https://github.com/readium/r2-shared-swift/issues/158

**Comment by alexwhb** [comment]
@mickael-menu Thanks for getting back to me. Ya my use case is purely displaying EPUBs for the time being. I'd ideally like to display them even when not downloaded to the a device, but have implemented a downloader mechanism for the time being if that's not possible.  And as to the Fetcher... that looks like exactly what I was missing. Thank you for that info! that's super helpful. I'm going to play with that. Btw love the project. You guys are killing it. Hopefully someday I will understand it well enough to contribute. At this point though I'm just enjoying the simplicity of implementing what would have taken me easily a year or more to implement on my own.

**Comment by mickael-menu** [comment]
> Ya my use case is purely displaying EPUBs for the time being. I'd ideally like to display them even when not downloaded to the a device, but have implemented a downloader mechanism for the time being if that's not possible.

If the EPUB is exploded on the server, you should be able to make it work with a custom `PublicationAsset` + the `HTTPFetcher`. However if it's the full compressed EPUB file that is served, it's not going to work because the ZIP library we use doesn't handle remote archives. You could provide a custom implementation of `Archive`, but I think that would be quite complicated.

> Btw love the project. You guys are killing it. Hopefully someday I will understand it well enough to contribute. At this point though I'm just enjoying the simplicity of implementing what would have taken me easily a year or more to implement on my own.

Thanks, contributions are most welcome!

> One quick question... a bit off topic, are you guys planning on implementing media overlays in this library? I know the web player has them, so I'm curious if that's in the road map for the future.

Yes it's on the roadmap.

**Pull request merged**
